# Generated by Django 6.0.4 on 2026-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
