# Generated by Django 6.0.4 on 2026-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='Uzbekistan', max_length=100, null=True),
        ),
    ]
