# Generated by Django 6.0.4 on 2026-04-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='finished_at',
            new_name='end_date',
        ),
    ]
