# Generated by Django 6.0.4 on 2026-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_finished_at_discount_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
