# Generated by Django 6.0.4 on 2026-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_review_user_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
